# Generated by Django 4.2.18 on 2026-07-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brevo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
