# Generated by Django 4.2.18 on 2026-01-04 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('endpoint', models.CharField(choices=[('coordinate_access', 'Coordinate Access')], db_index=True, max_length=50)),
                ('violation_count', models.IntegerField(default=1)),
                ('first_violation_at', models.DateTimeField(auto_now_add=True)),
                ('last_violation_at', models.DateTimeField(auto_now=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User if authenticated during violation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Limit Violation',
                'verbose_name_plural': 'Rate Limit Violations',
                'indexes': [models.Index(fields=['ip_address', 'endpoint', 'last_violation_at'], name='app_ratelim_ip_addr_c19b58_idx')],
                'unique_together': {('ip_address', 'endpoint')},
            },
        ),
    ]
