# Generated by Django 4.2.18 on 2026-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='cooldown_until',
        ),
    ]
