# Generated by Django 4.2.18 on 2026-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ratelimitviolation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='endpoint',
            field=models.CharField(choices=[('COORDINATE_ACCESS', 'Coordinate Access')], db_index=True, max_length=50),
        ),
    ]
