# Generated by Django 4.2.18 on 2026-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ratelimitviolation_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='first_violation_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='last_violation_at',
            field=models.DateTimeField(),
        ),
    ]
