# Generated by Django 4.2.18 on 2026-01-18 10:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_remove_auto_now_from_violation_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimitviolation',
            name='user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='RateLimitAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('violation_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('appealed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_appeals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app.ratelimitviolation')),
            ],
            options={
                'verbose_name': 'Rate Limit Appeal',
                'verbose_name_plural': 'Rate Limit Appeals',
                'ordering': ['-created_at'],
            },
        ),
    ]
