# Generated by Django 4.2.18 on 2026-01-27 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_ratelimitviolation_user_ids_ratelimitappeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('state_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Abuse Appeal',
                'verbose_name_plural': 'Abuse Appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbuseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('last_points_update_at', models.DateTimeField(auto_now_add=True)),
                ('episode_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('sensitive_count_in_episode', models.PositiveIntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abuse State',
                'verbose_name_plural': 'Abuse States',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitviolation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='user',
        ),
        migrations.DeleteModel(
            name='RateLimitAppeal',
        ),
        migrations.DeleteModel(
            name='RateLimitViolation',
        ),
        migrations.AddField(
            model_name='abuseappeal',
            name='abuse_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app.abusestate'),
        ),
        migrations.AddField(
            model_name='abuseappeal',
            name='appealed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abuseappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
