# Generated by Django 4.2.18 on 2026-01-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_permanently_banned_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abuseappeal',
            name='appealed_by',
        ),
    ]
