# Generated by Django 4.2.18 on 2026-01-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_appealed_by_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlacesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('autocomplete_requests', models.PositiveIntegerField(default=0)),
                ('details_requests', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Google Places Usage',
                'verbose_name_plural': 'Google Places Usage',
            },
        ),
        migrations.CreateModel(
            name='GooglePlacesUserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('autocomplete_requests', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Places User Usage',
                'verbose_name_plural': 'Google Places User Usage',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
