# Generated by Django 4.2.18 on 2026-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_sensitive_count_to_points_in_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusestate',
            name='captcha_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
