version: "3.7"

services:
  dev:
    image: eznashdb-dev-image:latest
    command:
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - .:/app:rw
      - $HOME/.local-overrides:/home/docker/.config/local-overrides
      # - $HOME/.cache/devcontainer:/home/docker/.cache/devcontainer
