# Generated by Django 4.0.1 on 2022-02-17 18:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eznashdb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shul",
            old_name="editted_by",
            new_name="updated_by",
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="shul",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="shul",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
