# Generated by Django 4.0.1 on 2022-11-30 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0004_alter_room_created_at_alter_room_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shul",
            name="city",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
