# Generated by Django 4.0.1 on 2023-05-21 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0008_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_centered",
        ),
    ]
