# Generated by Django 4.0.1 on 2023-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eznashdb', '0009_remove_room_is_centered'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_balcony',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
