# Generated by Django 4.0.1 on 2023-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0011_remove_room_is_balcony_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[("XS", "Much smaller"), ("S", "Smaller"), ("M", "Same size"), ("L", "Larger")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Very difficult"),
                    ("2", "Difficult"),
                    ("3", "Moderate"),
                    ("4", "Easy"),
                    ("5", "Very easy"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
