# Generated by Django 4.0.1 on 2023-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0012_alter_room_relative_size_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="is_wheelchair_accessible",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
