# Generated by Django 4.0.1 on 2023-06-11 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eznashdb", "0014_rename_is_same_floor_back_room_is_elevated_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shul",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_shuls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
