# Generated by Django 4.0.1 on 2023-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0015_alter_room_created_by_alter_shul_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Less than half"),
                    ("S", "Smaller, but at least half"),
                    ("M", "Same size"),
                    ("L", "Larger"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
