# Generated by Django 4.0.1 on 2023-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0016_alter_room_relative_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="is_wheelchair_accessible",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
