# Generated by Django 4.0.1 on 2023-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0017_alter_room_is_wheelchair_accessible"),
    ]

    operations = [
        migrations.AddField(
            model_name="shul",
            name="address",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
