# Generated by Django 4.0.1 on 2023-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0018_shul_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shul",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
