# Generated by Django 4.0.1 on 2023-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0019_alter_shul_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="shul",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
