# Generated by Django 4.0.1 on 2023-11-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0021_shul_latitude_shul_longitude_shul_place_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                (
                    "shul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="eznashdb.shul",
                    ),
                ),
            ],
            options={
                "verbose_name": "link",
                "verbose_name_plural": "links",
            },
        ),
    ]
