# Generated by Django 4.0.1 on 2023-12-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0023_auto_20231209_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Less than half"),
                    ("M", "Smaller, but at least half"),
                    ("L", "Same size or larger"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
