# Generated by Django 4.0.1 on 2023-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0024_alter_room_relative_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S - Less than half"),
                    ("M", "M - Smaller, but at least half"),
                    ("L", "L - Same size or larger"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
