# Generated by Django 4.0.1 on 2023-12-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0026_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildcareProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("age_min", models.IntegerField(blank=True, null=True)),
                ("age_max", models.IntegerField(blank=True, null=True)),
                ("supervision_required", models.BooleanField(blank=True, null=True)),
                (
                    "shul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="childcare_programs",
                        to="eznashdb.shul",
                    ),
                ),
            ],
            options={
                "verbose_name": "childcare program",
                "verbose_name_plural": "childcare programs",
            },
        ),
    ]
