# Generated by Django 4.0.1 on 2023-12-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0027_childcareprogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="childcareprogram",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL", "All of shacharit and mussaf on shabbat"),
                    ("PART", "Part of shacharit and mussaf on shabbat"),
                ],
                max_length=20,
            ),
        ),
    ]
