# Generated by Django 4.0.1 on 2023-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0028_childcareprogram_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5", "5 (Equal)"),
                    ("4", "4"),
                    ("3", "3"),
                    ("2", "2"),
                    ("1", "1 (Much more difficult)"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
