# Generated by Django 4.0.1 on 2023-12-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0029_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="childcareprogram",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
