# Generated by Django 4.0.1 on 2023-12-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0030_childcareprogram_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childcareprogram",
            name="duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL", "All of shabbat shacharit and mussaf"),
                    ("PART", "Part of shabbat shacharit and mussaf"),
                ],
                max_length=20,
            ),
        ),
    ]
