# Generated by Django 4.0.1 on 2023-12-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0031_alter_childcareprogram_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childcareprogram",
            name="age_max",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="childcareprogram",
            name="age_min",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                ],
                null=True,
            ),
        ),
    ]
