# Generated by Django 4.0.1 on 2024-01-01 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0033_rename_age_max_childcareprogram_max_age_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="childcareprogram",
            options={
                "ordering": ["min_age", "max_age"],
                "verbose_name": "childcare program",
                "verbose_name_plural": "childcare programs",
            },
        ),
    ]
