# Generated by Django 4.0.1 on 2024-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0034_alter_childcareprogram_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shul",
            name="has_childcare",
        ),
        migrations.AddField(
            model_name="shul",
            name="has_no_childcare",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
