# Generated by Django 4.2.18 on 2025-11-09 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0036_alter_room_relative_size_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_wheelchair_accessible",
        ),
    ]
