# Generated by Django 4.2.18 on 2025-11-09 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0037_remove_room_is_wheelchair_accessible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shul",
            name="has_female_leadership",
        ),
    ]
