# Generated by Django 4.2.18 on 2025-11-09 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0038_remove_shul_has_female_leadership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shul",
            name="can_say_kaddish",
        ),
    ]
