# Generated by Django 4.2.18 on 2025-11-09 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0039_remove_shul_can_say_kaddish"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShulLink",
        ),
    ]
