# Generated by Django 4.2.18 on 2025-11-09 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0040_delete_shullink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shul",
            name="has_no_childcare",
        ),
        migrations.DeleteModel(
            name="ChildcareProgram",
        ),
    ]
