# Generated by Django 4.2.18 on 2025-11-09 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0041_remove_shul_has_no_childcare_delete_childcareprogram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_balcony",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_elevated_back",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_elevated_side",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_mixed_seating",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_only_men",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_same_height_back",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_same_height_side",
        ),
    ]
