# Generated by Django 4.2.18 on 2025-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0042_remove_room_is_balcony_remove_room_is_elevated_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "5",
                        "<small><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i> (5)</small>",
                    ),
                    (
                        "4",
                        "<small><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i> (4)</small>",
                    ),
                    (
                        "3",
                        "<small><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i> (3)</small>",
                    ),
                    (
                        "2",
                        "<small><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i> (2)</small>",
                    ),
                    (
                        "1",
                        "<small><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i> (1)</small>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
