# Generated by Django 4.2.18 on 2025-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0043_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "<kbd>L</kbd><small> - Same size or larger</small>"),
                    ("M", "<kbd>M</kbd><small> - Smaller, but at least half</small>"),
                    ("S", "<kbd>S</kbd><small> - Less than half</small>"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
