# Generated by Django 4.2.18 on 2025-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0044_alter_room_relative_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L",
                        "<span class='text-nowrap'><kbd>L</kbd><small> - Same size or larger</small></span>",
                    ),
                    (
                        "M",
                        "<span class='text-nowrap'><kbd>M</kbd><small> - Smaller, but at least half</small></span>",
                    ),
                    (
                        "S",
                        "<span class='text-nowrap'><kbd>S</kbd><small> - Less than half</small></span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
