# Generated by Django 4.2.18 on 2025-11-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0046_alter_room_relative_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L",
                        "<span class='text-nowrap'><kbd class='fw-bold'>L</kbd><small> - Same size or larger</small></span>",
                    ),
                    (
                        "M",
                        "<span class='text-nowrap'><kbd class='fw-bold'>M</kbd><small> - Smaller, but at least half</small></span>",
                    ),
                    (
                        "S",
                        "<span class='text-nowrap'><kbd class='fw-bold'>S</kbd><small> - Less than half</small></span>",
                    ),
                    (
                        "X",
                        "<span class='text-nowrap'><kbd class='fw-bold'>X</kbd><small> - No women's section</small></span>",
                    ),
                    (
                        "&",
                        "<span class='text-nowrap'><kbd class='fw-bold'>&</kbd><small> - Mixed seating</small></span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "5",
                        "<span class='text-nowrap'><kbd class='fw-bold'>5</kbd> <small> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i></small></span>",
                    ),
                    (
                        "4",
                        "<span class='text-nowrap'><kbd class='fw-bold'>4</kbd> <small> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></small></span>",
                    ),
                    (
                        "3",
                        "<span class='text-nowrap'><kbd class='fw-bold'>3</kbd> <small> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></small></span>",
                    ),
                    (
                        "2",
                        "<span class='text-nowrap'><kbd class='fw-bold'>2</kbd> <small> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></small></span>",
                    ),
                    (
                        "1",
                        "<span class='text-nowrap'><kbd class='fw-bold'>1</kbd> <small> - <i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></small></span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
