# Generated by Django 4.2.18 on 2025-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0047_alter_room_relative_size_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shul",
            name="latitude",
            field=models.DecimalField(decimal_places=17, max_digits=22),
        ),
        migrations.AlterField(
            model_name="shul",
            name="longitude",
            field=models.DecimalField(decimal_places=17, max_digits=22),
        ),
    ]
