# Generated by Django 4.2.18 on 2025-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0048_alter_shul_latitude_alter_shul_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L",
                        "<span class='text-nowrap'><kbd class='fw-bold'>L</kbd><small> - Equal or larger than men's</small></span>",
                    ),
                    (
                        "M",
                        "<span class='text-nowrap'><kbd class='fw-bold'>M</kbd><small> - At least half men's size</small></span>",
                    ),
                    (
                        "S",
                        "<span class='text-nowrap'><kbd class='fw-bold'>S</kbd><small> - Less than half men's size</small></span>",
                    ),
                    (
                        "X",
                        "<span class='text-nowrap'><kbd class='fw-bold'>X</kbd><small> - No women's section</small></span>",
                    ),
                    (
                        "&",
                        "<span class='text-nowrap'><kbd class='fw-bold'>&</kbd><small> - Mixed seating</small></span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
