# Generated by Django 4.2.18 on 2025-11-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0049_alter_room_relative_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "L",
                        "<span class='text-nowrap'><kbd class='fw-bold'>L</kbd> - Equal or larger than men's</span>",
                    ),
                    (
                        "M",
                        "<span class='text-nowrap'><kbd class='fw-bold'>M</kbd> - At least half men's size</span>",
                    ),
                    (
                        "S",
                        "<span class='text-nowrap'><kbd class='fw-bold'>S</kbd> - Less than half men's size</span>",
                    ),
                    (
                        "X",
                        "<span class='text-nowrap'><kbd class='fw-bold'>X</kbd> - No women's section</span>",
                    ),
                    (
                        "&",
                        "<span class='text-nowrap'><kbd class='fw-bold'>&</kbd> - Mixed seating</span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "5",
                        "<span class='text-nowrap'><kbd class='fw-bold'>5</kbd> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i></span>",
                    ),
                    (
                        "4",
                        "<span class='text-nowrap'><kbd class='fw-bold'>4</kbd> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></span>",
                    ),
                    (
                        "3",
                        "<span class='text-nowrap'><kbd class='fw-bold'>3</kbd> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></span>",
                    ),
                    (
                        "2",
                        "<span class='text-nowrap'><kbd class='fw-bold'>2</kbd> - <i class='fa-solid fa-star text-warning'></i><i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></span>",
                    ),
                    (
                        "1",
                        "<span class='text-nowrap'><kbd class='fw-bold'>1</kbd> - <i class='fa-solid fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i><i class='fa-regular fa-star text-warning'></i></span>",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
