# Generated by Django 4.2.18 on 2025-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0050_alter_room_relative_size_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="relative_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Equal or larger than men's"),
                    ("M", "At least half men's size"),
                    ("S", "Less than half men's size"),
                    ("X", "No women's section"),
                    ("&", "Mixed seating"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="see_hear_score",
            field=models.CharField(
                blank=True,
                choices=[("5", " 5"), ("4", " 4"), ("3", " 3"), ("2", " 2"), ("1", " 1")],
                default="",
                max_length=50,
            ),
        ),
    ]
