# Generated by Django 4.2.18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0051_alter_room_relative_size_alter_room_see_hear_score"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shul",
            index=models.Index(fields=["name"], name="shul_name_idx"),
        ),
    ]
