# Generated by Django 4.2.18 on 2026-01-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eznashdb", "0053_shul_deleted_shul_deleted_by_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="shul",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_shuls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shul",
            name="deletion_reason",
            field=models.TextField(blank=True),
        ),
    ]
