# Generated by Django 4.2.18 on 2026-01-15 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0054_shul_deleted_by_shul_deletion_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedShul",
            fields=[],
            options={
                "verbose_name": "deleted shul",
                "verbose_name_plural": "deleted shuls",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eznashdb.shul",),
        ),
    ]
