# Generated by Django 4.2.18 on 2026-07-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0055_deletedshul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shul",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
