# Generated by Django 4.2.18 on 2026-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0056_alter_room_name_alter_shul_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shul",
            name="has_man_join_kaddish",
            field=models.CharField(
                blank=True, choices=[("YES", "Yes"), ("NO", "No")], default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="shul",
            name="is_kaddish_allowed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALONE_OR_WITH_MEN", "Yes – alone or with men"),
                    ("WITH_MEN_ONLY", "Yes – only with men"),
                    ("NO", "No"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
