# Generated by Django 4.2.18 on 2026-07-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0057_shul_has_man_join_kaddish_shul_is_kaddish_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shul",
            name="is_kaddish_allowed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALONE_OR_WITH_MEN", "Yes (alone or with men)"),
                    ("WITH_MEN_ONLY", "Only with men"),
                    ("NO", "No"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
