# Generated by Django 4.2.18 on 2026-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0058_alter_shul_is_kaddish_allowed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shul",
            name="has_man_join_kaddish",
        ),
        migrations.RemoveField(
            model_name="shul",
            name="is_kaddish_allowed",
        ),
        migrations.AddField(
            model_name="shul",
            name="kaddish_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAN_SAY_ALONE", "Yes, can say alone"),
                    ("SHUL_ENSURES_MAN", "Yes, shul ensures a man always joins"),
                    ("ONLY_IF_MAN", "Only if a man joins, need to coordinate"),
                    ("NO", "No"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
