# Generated by Django 4.2.18 on 2026-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0060_alter_shul_kaddish_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shul",
            name="kaddish_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAN_SAY_ALONE", "Can say alone"),
                    ("SHUL_ENSURES_MAN", "Shul ensures a man will join"),
                    ("ONLY_IF_MAN", "Only with men, need to coordinate"),
                    ("NO", "Not allowed"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
