# Generated by Django 4.2.18 on 2026-10-03 17:11

from django.db import migrations, models

import eznashdb.contact


class Migration(migrations.Migration):
    dependencies = [
        ("eznashdb", "0063_alter_shul_kaddish_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="shul",
            name="contact",
            field=models.CharField(
                blank=True, default="", max_length=255, validators=[eznashdb.contact.validate_contact]
            ),
        ),
    ]
